### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by propi** [opendatacz/pc-filing-app#23] opened 2014-07-22 18:36 UTC
In supplier-calls.jsp, if you click to the "First" button within pagination, the application throws javascript error.

**Comment by jindrichmynarz** [comment] 2014-07-22 19:06
I cannot reproduce this error on http://lod2.vse.cz:8090. Please describe in more detail how to reproduce it.

**Comment by propi** [comment] 2014-07-22 22:16
I don't understand it! Now it works! It was probably some random, strange and irreproducible error:)

**Comment by jindrichmynarz** [comment] 2014-07-23 07:02
Closing as not reproducible.

**Comment by propi** [comment] 2014-07-30 10:06
"javascript exception: invalid date" when I click to the first page button...

**Closed as completed** 2014-08-01 21:57 UTC
Labels: bug
