### ISSUE TITLE
Contracting authority's calls do not display

### ISSUE THREAD

**Issue by jakhrkal** [opendatacz/pc-filing-app#53] opened 2014-08-21 08:26 UTC
When logged in as a contracting authority, my Calls in preparation, Published calls and Cancelled calls (http://lod2.vse.cz:8080/pc-filing-app/buyer-prepared.jsp , http://lod2.vse.cz:8080/pc-filing-app/buyer-published.jsp , http://lod2.vse.cz:8080/pc-filing-app/buyer-cancelled.jsp ) do not display at all.
FF console output:
[16:14:57.476] GET http://lod2.vse.cz:8080/pc-filing-app/buyer-prepared.jsp [HTTP/1.1 200 OK 73ms]
[16:14:59.477] GET http://lod2.vse.cz:8080/pc-filing-app/js/cpv-codes-cs.js [HTTP/1.1 304 Not Modified 23ms]
[16:14:58.640] Unknown property 'box-sizing'.  Declaration dropped. @ http://lod2.vse.cz:8080/pc-filing-app/buyer-prepared.jsp
[16:14:59.697] GET http://lod2.vse.cz:8080/pc-filing-app/SystemManager?action=getUserPreferences [HTTP/1.1 200 OK 23ms]
[16:14:59.699] GET http://lod2.vse.cz:8080/pc-filing-app/PCFilingApp?action=table&items=10&page=0&tableName=PrivateContracts&reload=true [HTTP/1.1 200 OK 113ms]
[16:14:58.891] ReferenceError: cpvs is not defined @ http://lod2.vse.cz:8080/pc-filing-app/js/table.js:228

![screenshot-2](https://cloud.githubusercontent.com/assets/7760136/3993448/bf45261e-290c-11e4-95b0-c2a4742ea3e7.png)

**Comment by jindrichmynarz** [comment] 2014-08-21 09:19
For this and any following issues, please add:
- exact URL from the browser's address bar of the page, where the issue occurs
- the output of the browser's console

Having such information helps to replicate the issue and identify the error occurring.

**Comment by jindrichmynarz** [comment] 2014-08-21 17:35
I believe this was fixed by a889a1e31127730688d802c6142e0401a3deed41. Now I can't reproduce the issue at http://lod2.vse.cz:8080/pc-filing-app/. Please re-check it and close the issue if it's resolved.

**Closed as completed** 2014-08-22 12:48 UTC
Labels: bug
